name: Check version

outputs:
  publish-version:
    description: Version of the published artifacts
    value: ${{ steps.check-version.outputs.publish-version }}
  is-release:
    description: Whether publish a release or not
    value: ${{ steps.check-version.outputs.is-release }}

runs:
  using: "composite"
  steps:
    - name: Check for desired version of published artifacts
      id: check-version
      run: |
        BRANCH_NAME="${GITHUB_REF#refs/heads/}"
        echo "Setting BRANCH_NAME=$BRANCH_NAME"

        BRANCH_NAME=`echo $BRANCH_NAME | sed "s/[^[:alnum:]-]//g" | tr '[:upper:]' '[:lower:]'` # lowercase, only alphanumeric and dash

        REPO_VERSION_MOST_RECENT=$(git describe --tags --always --abbrev=0)
        REPO_VERSION_DESIRED=$(cargo pkgid --manifest-path Cargo.toml | cut -d# -f2 | cut -d: -f2)
        echo "Highest released version was: $REPO_VERSION_MOST_RECENT, desired version is $REPO_VERSION_DESIRED"

        IS_RELEASE="false"

        if [[ "${{ github.event_name }}" == "push" ]]; then
          if [[ "$BRANCH_NAME" == "master" && "$REPO_VERSION_DESIRED" != "$REPO_VERSION_MOST_RECENT" ]]; then
            PUBLISH_VERSION="$REPO_VERSION_DESIRED"
            IS_RELEASE="true"
            echo "This is push to main, and version was bumped from $REPO_VERSION_MOST_RECENT to $REPO_VERSION_DESIRED. Will publish a release of $REPO_VERSION_DESIRED."
          fi;
        fi;

        if [[ -z "$PUBLISH_VERSION" ]]; then
          PUBLISH_VERSION="$REPO_VERSION_MOST_RECENT-$BRANCH_NAME-${{ github.run_number }}"
        fi;

        echo "CI will publish artifacts at version: $PUBLISH_VERSION"

        echo "::set-output name=publish-version::$PUBLISH_VERSION"
        echo "::set-output name=is-release::$IS_RELEASE"
      shell: bash
